name: github-actions-react-app
on: push
jobs:
  github-actions-react-application:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v4
        with: 
          node-version: 23
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
