name: react-app-github-actions-context
on: workflow_dispatch
jobs: 
  github-actions-context:
    runs-on: macos-latest
    steps:
      - name: Output Github Actions Context
        run: echo "${{ toJSON(github) }}"
